# -----------------------------------------------------
#  Copyright Iliass Mahjoub 2022.                     
#  Distributed under the Boost Software License,      
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)   
# -----------------------------------------------------
---
engines:
  cppcheck:
    language: c++
exclude_paths:
  - "**README.md"